# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: murdoc 0.1.13 ruby lib

Gem::Specification.new do |s|
  s.name = "murdoc"
  s.version = "0.1.13"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Mark Abramov"]
  s.date = "2015-07-06"
  s.description = "Annotated documentation generator, see README.md for details"
  s.email = "markizko@gmail.com"
  s.executables = ["murdoc", "murdoc-strip-comments"]
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    ".travis.yml",
    "Gemfile",
    "Gemfile.lock",
    "README.md",
    "Rakefile",
    "UNLICENSE",
    "VERSION",
    "autotest/discover.rb",
    "bin/murdoc",
    "bin/murdoc-strip-comments",
    "lib/murdoc.rb",
    "lib/murdoc/annotator.rb",
    "lib/murdoc/formatter.rb",
    "lib/murdoc/languages/html.rb",
    "lib/murdoc/languages/javascript.rb",
    "lib/murdoc/languages/ruby.rb",
    "lib/murdoc/paragraph.rb",
    "markup/stylesheet.css",
    "markup/template.haml",
    "markup/template_multifile.haml",
    "murdoc.gemspec",
    "spec/murdoc/annotator_spec.rb",
    "spec/murdoc/formatter_spec.rb",
    "spec/murdoc/paragraph_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/markiz/murdoc"
  s.licenses = ["Public Domain"]
  s.rubygems_version = "2.4.5"
  s.summary = "Annotated documentation generator"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<kramdown>, [">= 0"])
      s.add_runtime_dependency(%q<haml>, ["~> 3.0.0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.4.0"])
      s.add_development_dependency(%q<rdiscount>, ["~> 1.6.5"])
    else
      s.add_dependency(%q<kramdown>, [">= 0"])
      s.add_dependency(%q<haml>, ["~> 3.0.0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<rspec>, ["~> 2.4.0"])
      s.add_dependency(%q<rdiscount>, ["~> 1.6.5"])
    end
  else
    s.add_dependency(%q<kramdown>, [">= 0"])
    s.add_dependency(%q<haml>, ["~> 3.0.0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<rspec>, ["~> 2.4.0"])
    s.add_dependency(%q<rdiscount>, ["~> 1.6.5"])
  end
end

